name: Validation on MicroK8s
on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Kubernetes version to be used for Microk8s.'
        required: false
      uats_branch:
        description: 'Branch to run the UATs from e.g. main or track/1.10. By default, this is defined by the dependencies.yaml file.'
        required: false
      ckf_branch:
        description: 'Branch on the Charmed Kubeflow repository to be tested'
        required: false
      risk:
        description: 'The risk level to be tested'
        required: false
        default: 'stable'

  pull_request:
  schedule:
    - cron: "17 02 * * 1"

jobs:
  deploy-solution:
    name: Deploy to Microk8s
    runs-on: ["self-hosted-linux-amd64-jammy-xlarge"]

    strategy:
      fail-fast: false
      matrix:
        bundle:
          - module: kubeflow-mlflow
            uats:
              env: uats-remote
              extra-args: --filter "not feast and not spark" --include-kubeflow-trainer-tests
          - module: kubeflow-feast
            uats:
              env: feast-remote
              extra-args: ""
          - module: kubeflow-spark
            risk: edge # TODO: Run Spark tests with Kubeflow from `stable` risk once all changes for Spark integration are released to stable
            tf-vars-file: examples/tfvars.json
            uats:
              env: spark-remote
              extra-args: --test-image ghcr.io/canonical/charmed-spark-jupyterlab:3.5-22.04_edge@sha256:72a6e89985e35e0920fb40c063b3287425760ebf823b129a87143d5ec0e99af7
        pod-security-standards:
          - policy: privileged
            istio-cni-bin-dir: ""  # meaning Istio CNI disabled
            istio-cni-conf-dir: ""  # meaning Istio CNI disabled
          - policy: baseline
            istio-cni-bin-dir: /var/snap/microk8s/current/opt/cni/bin
            istio-cni-conf-dir: /var/snap/microk8s/current/args/cni-network

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set envvars from dependencies.yaml
        run: |
          yq eval 'to_entries | .[] | "\(.key)=\(.value)"' ".github/dependencies.yaml" | while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done

      - name: Update ENV variables from inputs if available
        run: |
          K8S_VERSION=${{ inputs.k8s_version || env.K8S_VERSION }}
          echo "K8S_VERSION=${K8S_VERSION}" >> $GITHUB_ENV
          CKF_BRANCH=${{ inputs.ckf_branch || env.CKF_BRANCH }}
          echo "CKF_BRANCH=${CKF_BRANCH}" >> $GITHUB_ENV
          RISK=${{ matrix.bundle.risk || inputs.risk }}
          echo "RISK=${RISK}" >> $GITHUB_ENV

          UATS_BRANCH=${{ matrix.bundle.uats_branch || inputs.uats_branch || env.UATS_BRANCH }}
          echo "UATS_BRANCH=${UATS_BRANCH}" >> $GITHUB_ENV

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          architecture: x64

      - name: Install tox & poetry
        run: |
          pip install tox
          pip install poetry

      - name: Setup operator environment
        run: |
          # NOTE: bacause of this issue...
          # https://github.com/canonical/istio-operators/issues/656
          # ...non-strict MicroK8s is required for Istio CNI to be functional,
          # and Juju does not support non-strict MicroK8s snaps unless manually
          # added to Juju as K8s clouds like this...
          # `sudo microk8s config | juju add-k8s local-k8s --client`
          # ...which neither the action `charmed-kubernetes/actions-operator`
          # nor the `concierge` snap support configuring as of today

          sudo snap refresh
          sudo snap install juju --channel=${{ env.JUJU_VERSION }}/stable --classic
          sudo snap install charmcraft --channel=3.x/stable --classic
          sudo snap install microk8s --channel=${{ env.K8S_VERSION }}/stable --classic

          sudo snap alias microk8s.kubectl kubectl
          sudo usermod -a -G microk8s $USER
          newgrp microk8s

          # avoiding Docker Hub's image pull rate limits - see:
          # https://canonical-self-hosted-github-runner-docs.readthedocs-hosted.com/en/latest/usage/faq/how-to-avoid-dockerhub-rate-limits
          if [ -n "$DOCKERHUB_MIRROR" ]; then
          MIRROR_CONFIG=/var/snap/microk8s/current/args/certs.d/docker.io
          sudo mkdir -p ${MIRROR_CONFIG}
          sudo chown $USER ${MIRROR_CONFIG}
          cat << EOF > ${MIRROR_CONFIG}/hosts.toml
          [host."$DOCKERHUB_MIRROR"]
          capabilities = ["pull", "resolve"]
          EOF
          fi
          microk8s status --wait-ready
          sudo microk8s stop
          sudo microk8s start

          microk8s status --wait-ready
          sudo microk8s enable dns hostpath-storage rbac metallb:10.64.140.43-10.64.140.49
          microk8s status --wait-ready

          # a workaround for Juju 3's strict snap:
          mkdir -p ~/.local/share/juju

          sudo microk8s config | juju add-k8s local-k8s --client

          juju bootstrap local-k8s microk8s

          # for Python's K8s client to find K8s configurations without code or
          # environment-variable changes:
          microk8s config > ~/.kube/config

      - name: Setup terraform
        run: |
          sudo snap install terraform --channel latest/stable --classic
          terraform --version

      - name: Deploy solution
        run: |
          if [[ '${{ github.event_name }}' != 'pull_request' ]]; then
            git checkout '${{ env.CKF_BRANCH }}'
          fi

          TF_VARS_ARG=""
          if [[ -n "${{ matrix.bundle.tf-vars-file }}" ]]; then
            TF_VARS_ARG="--tf-vars-file ${{ matrix.bundle.tf-vars-file }}"
          fi

          tox -c ./modules/${{ matrix.bundle.module }} -e test_deployment -- -vv -s --risk ${{ env.RISK }} --istio-cni-bin-dir ${{ matrix.pod-security-standards.istio-cni-bin-dir }} --istio-cni-conf-dir ${{ matrix.pod-security-standards.istio-cni-conf-dir }} --pss ${{ matrix.pod-security-standards.policy }} $TF_VARS_ARG

      - name: Run UATs
        run: |
          git clone https://github.com/canonical/charmed-kubeflow-uats.git ~/charmed-kubeflow-uats
          cd ~/charmed-kubeflow-uats
          git checkout ${{ env.UATS_BRANCH }}
          tox -e ${{ matrix.bundle.uats.env }} -- --security-policy ${{ matrix.pod-security-standards.policy }} ${{ matrix.bundle.uats.extra-args }}

      # On failure, capture debugging resources
      - name: Select model
        run: juju switch kubeflow
        if: failure() || cancelled()

      - name: Get juju status
        run: juju status
        if: failure() || cancelled()

      - name: Get juju debug logs
        run: juju debug-log --replay --no-tail
        if: failure() || cancelled()

      - name: Get all kubernetes resources
        run: kubectl get all -A
        if: failure() || cancelled()

      - name: Describe all pods
        if: failure() || cancelled()
        run: kubectl describe pods --all-namespaces

      - name: Get logs from pods with status = Pending
        run: kubectl -n kubeflow get pods | tail -n +2 | grep Pending | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100 || true
        if: failure() || cancelled()

      - name: Get logs from pods with status = Failed
        run: kubectl -n kubeflow get pods | tail -n +2 | grep Failed | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100 || true
        if: failure() || cancelled()

      - name: Get logs from pods with status = CrashLoopBackOff
        run: kubectl -n kubeflow get pods | tail -n +2 | grep CrashLoopBackOff | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100 || true
        if: failure() || cancelled()
